# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import central_pb2 as central__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in central_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CentralAtendimentoStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarHorario = channel.unary_unary(
                '/central.CentralAtendimento/ConsultarHorario',
                request_serializer=central__pb2.PerguntaHorario.SerializeToString,
                response_deserializer=central__pb2.RespostaHorario.FromString,
                _registered_method=True)
        self.AcompanharAvisos = channel.unary_stream(
                '/central.CentralAtendimento/AcompanharAvisos',
                request_serializer=central__pb2.InscricaoAvisos.SerializeToString,
                response_deserializer=central__pb2.Aviso.FromString,
                _registered_method=True)


class CentralAtendimentoServicer:
    """Missing associated documentation comment in .proto file."""

    def ConsultarHorario(self, request, context):
        """RPC unário: uma pergunta, uma resposta - "parece" uma chamada de função comum
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcompanharAvisos(self, request, context):
        """RPC com streaming de servidor: uma inscrição, várias respostas ao longo do tempo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralAtendimentoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarHorario': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarHorario,
                    request_deserializer=central__pb2.PerguntaHorario.FromString,
                    response_serializer=central__pb2.RespostaHorario.SerializeToString,
            ),
            'AcompanharAvisos': grpc.unary_stream_rpc_method_handler(
                    servicer.AcompanharAvisos,
                    request_deserializer=central__pb2.InscricaoAvisos.FromString,
                    response_serializer=central__pb2.Aviso.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'central.CentralAtendimento', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('central.CentralAtendimento', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentralAtendimento:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarHorario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/central.CentralAtendimento/ConsultarHorario',
            central__pb2.PerguntaHorario.SerializeToString,
            central__pb2.RespostaHorario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcompanharAvisos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/central.CentralAtendimento/AcompanharAvisos',
            central__pb2.InscricaoAvisos.SerializeToString,
            central__pb2.Aviso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
