# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: central.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'central.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcentral.proto\x12\x07\x63\x65ntral\"%\n\x0fPerguntaHorario\x12\x12\n\nnome_aluno\x18\x01 \x01(\t\":\n\x0fRespostaHorario\x12\x15\n\rhorario_atual\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"%\n\x0fInscricaoAvisos\x12\x12\n\nnome_aluno\x18\x01 \x01(\t\"&\n\x05\x41viso\x12\x0e\n\x06numero\x18\x01 \x01(\x05\x12\r\n\x05texto\x18\x02 \x01(\t2\x9c\x01\n\x12\x43\x65ntralAtendimento\x12\x46\n\x10\x43onsultarHorario\x12\x18.central.PerguntaHorario\x1a\x18.central.RespostaHorario\x12>\n\x10\x41\x63ompanharAvisos\x12\x18.central.InscricaoAvisos\x1a\x0e.central.Aviso0\x01\x42-\n\x1b\x62r.pucminas.labdamd.centralB\x0c\x43\x65ntralProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'central_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033br.pucminas.labdamd.centralB\014CentralProtoP\001'
  _globals['_PERGUNTAHORARIO']._serialized_start=26
  _globals['_PERGUNTAHORARIO']._serialized_end=63
  _globals['_RESPOSTAHORARIO']._serialized_start=65
  _globals['_RESPOSTAHORARIO']._serialized_end=123
  _globals['_INSCRICAOAVISOS']._serialized_start=125
  _globals['_INSCRICAOAVISOS']._serialized_end=162
  _globals['_AVISO']._serialized_start=164
  _globals['_AVISO']._serialized_end=202
  _globals['_CENTRALATENDIMENTO']._serialized_start=205
  _globals['_CENTRALATENDIMENTO']._serialized_end=361
# @@protoc_insertion_point(module_scope)
